### ISSUE TITLE
Is it possible to use Prax on a public Linux server?

### ISSUE THREAD

**Issue by l0010o0001l** [ysbaddaden/prax.cr#40]
Hello,

Is it possible to use Prax on a Linux VM that is exposed publicly? I am using nginx with an upstream directive pointing to a unix socket. How might someone link a deployed application via Prax, and map the `.dev` domain in `listen` and `server_name` nginx server blocks? Let me know if I'm crazy.

Thanks!

Tara

**Comment by ysbaddaden** [comment]
You may, but this isn't recommended. Prax is a tool to simplify some development (with bugs), not a general purpose rack-proxy tool. Prax may seriously lack in security behavior, since it's meant on a personal computer, not on a public server. You'll have better results with Nginx/Passenger for example.

**Comment by l0010o0001l** [comment]
Sweet, thanks for the speed response @ysbaddaden!
